# Generated by cucumber-sinatra. (2014-04-05 15:15:59 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/monea_food.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = EatCode

class ToolupWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  EatCodeWorld.new
end
